### ISSUE TITLE
List three reasons for and against using Golang

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#10]
Suggest a back-end framework we could use, using Golang, and why use this over other languages.

**Comment by Jojokats** [comment]
## Advantages for using Golang:
1- Go is designed and supported by Google and is open source. Go is also used by some big companies like
	•	Google
	•	Dropbox
	•	Soundcloud
	•	Docker
	•	Cloudflare
	•	BBC

2- Golang has the speed of a compiled language, but the feel of an interpreted language. So you can write the code fast, and even faster compilation speeds allow for a rapid feedback style.

3- Golang has clean syntax with text-based workflow, minimalistic design, and clear language specification.

## Disadvantages for using Golang:
1- Go is still a very young language and has a very young ecosystem. This means there aren’t many libraries for it yet, leaving developers to write libraries themselves. There is also a shortage of books and online courses on the language.

2- It is still not so easy to learn Go and it’s difficult to handle errors in it.

3- Go’s tooling is really weird, on the surface it has some really nice tools, but a lot of them, when you start using them, quickly show their limitations.

**Comment by RichardLitt** [comment]
A shortage of resources for learning is a difficulty here! The speed and syntax would be great helps, though. I think for now we can say no, as this won't necessarily be the best place to start.
