### ISSUE TITLE
Book icon 

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#102]
Create book icon in svg format.

**Comment by RichardLitt** [comment]
Check out https://thenounproject.com/ and font awesome. Both of these should have books.

**Comment by Jojokats** [comment]
Already there lol

**Comment by RichardLitt** [comment]
Where will this icon be put?

**Comment by Jojokats** [comment]
@VernL suggested using it on the map to pinpoint the bookstores.

**Comment by RichardLitt** [comment]
Let's reopen this when we have a map. For now, this isn't needed.
