### ISSUE TITLE
Modification of info section.

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#103]
Hey @RichardLitt , 

Just modified the info section on the homepage to include a sign up input and removed the Contact button. I thought it could be important, since I will be including this in the Bookstore sidebar and thought that it should also be included in the homepage.

Let me know what you think. I have included an image.
Thanks!

![mailing](https://user-images.githubusercontent.com/10158712/32809208-080c3090-c964-11e7-9722-157970e8623f.png)

**Comment by RichardLitt** [comment]
Cool. I don't think we need the image. Maybe just the text?

**Comment by Jojokats** [comment]
> Cool. I don't think we need the image. Maybe just the text?

Sorry, don't understand what image you are referring to. I only added an input field and modified the text.

**Comment by RichardLitt** [comment]
What is the world map above?

**Comment by Jojokats** [comment]
> What is the world map above?

Above is the portfolio. Here is a screenshot of the whole page without the changes.

![travel-shelf-homepage](https://user-images.githubusercontent.com/10158712/32811928-60808d78-c970-11e7-9729-043ecd9a3a48.png)

**Comment by RichardLitt** [comment]
Cool. I would add you edits in a PR (you haven't added them yet, in this issue, unless there is a PR), remove the contact button, and add a GitHub button in the footer pointing to this repository. 

I would also remove the world map image - I don't think it adds to the design.

**Comment by Jojokats** [comment]
> I would also remove the world map image - I don't think it adds to the design.


The map image is really nice in my opinion and represents the independent bookstores that are included around the world. But it's your call.

**Comment by Jojokats** [comment]
Can I have the links to facebook, twitter & instagram?

**Comment by Jojokats** [comment]
Here is a screenshot of the icons. Let me know if this is ok. Thanks!

![screen shot 2017-11-14 at 7 33 05 pm](https://user-images.githubusercontent.com/10158712/32812398-bd71cd6a-c972-11e7-84ff-30b8b9336c5b.png)

**Comment by RichardLitt** [comment]
Put it last. Otherwise, that looks good!

We don't have a Facebook, Twitter, or Instagram yet. Dummy links? :)

**Comment by RichardLitt** [comment]
> The map image is really nice in my opinion and represents the independent bookstores that are included around the world. But it's your call.

@VernL and @ZJaf, what do you think?

**Comment by Jojokats** [comment]
My opinion again, but it visually communicates that we are targeting independent bookstores around the world with the global map image.
