### ISSUE TITLE
Bookstore page name

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#106]
Hey @RichardLitt,

I will be using the name drawnquarterly.html for the first bookpage.
Let me know if you have any other suggestions.

Thanks!

**Comment by RichardLitt** [comment]
Using that name will mean you set a precedent for manually setting the page names. This is not ideal, because we don't want to do manual work.

Instead, you should slugify the title of the bookstore and set it in the routes. Look at @VernL's new code and see if you can make a PR that does this.

**Comment by Jojokats** [comment]
> Instead, you should slugify the title of the bookstore and set it in the routes.

Not sure I understand.

**Comment by RichardLitt** [comment]
Can you please be more constructive in your comments about not understanding? It is good to know that you don't understand, but my inevitable comment will be "What do you not understand?". Please help me along. 

What do you not understand? What did you google before commenting?

**Comment by Jojokats** [comment]
> Can you please be more constructive in your comments about not understanding?

I haven't taken any backend courses so I'm a bit confused.
I googled: *how to slugify html and set it in the routes*
but am getting php / wordpress info.

Maybe I should contact @VernL to fix this.

**Comment by RichardLitt** [comment]
Cool. Those are two different things: "slugify", and "set routes." The second one will be harder to google - look at the routing code in @VernL's last merged PR. You mentioned that you were doing some express. That's where this will come in. 

If you are getting php and wordpress results, limit by using the term "javascript".

**Comment by Jojokats** [comment]
Maybe I should be including a `res` to a bookstore page, like in the bookstore.js file he coded:
```
var express = require('express')
var router = express.Router()
var bookstores = require('../models')

router.get('/', function (req, res, next) {
  res.json(bookstores)
})

module.exports = router
```
I'm guessing something like this, but not sure. I took a beginner Express code, but need to put it aside now to continue React
```
bookstore.get("/bookstore", function(req, res) {
   res.send(bookstore.html); 
});
```

I will look into it. Thanks

**Comment by Jojokats** [comment]
Just wondering if it's ok to use bookstore-1.html, bookstore-2... instead of the actual name.
Thanks,

**Comment by RichardLitt** [comment]
Nope. What does slugify mean?

**Comment by Jojokats** [comment]
Sorry for late reply but I’m away from my laptop and on my phone.
 I found this:
A slug is a few words that describe a post or a page. Slugs are usually a URL friendly version of the post title (which has been automatically generated by WordPress), but a slug can be anything you like. Slugs are meant to be used with permalinks as they help describe what the content at the URL is.

**Comment by RichardLitt** [comment]
Cool. That's close. Keep looking around, and remember, Wordpress answers will largely not help you. You're writing JavaScript, not php.

**Comment by Jojokats** [comment]
I found the following but it’s not helping me resolve my issue for the bookstore:HTML name 

Slugify" a string so it has only alphanumeric and hyphen characters. Useful for URLs and filenames. This is a JavaScript (node.js too) version of Recipe 577257.

Can you help?

**Comment by RichardLitt** [comment]
The most popular package for slugify on npm: https://www.npmjs.com/package/slugify
The second most popular: https://www.npmjs.com/package/slug
This SO thread: https://stackoverflow.com/questions/1053902/how-to-convert-a-title-to-a-url-slug-in-jquery

And, above:

> you should slugify the title of the bookstore

**Comment by Jojokats** [comment]
Thanks for the links, will look into them!

**Comment by Jojokats** [comment]
> you should slugify the title of the bookstore

I looked into the links and created a URL slug generator using jQuery.
Here is my [repo](https://github.com/Jojokats/URL-Slug) and below is the screenshot:

![slug-image](https://user-images.githubusercontent.com/10158712/32915613-7e9bc7fa-cae7-11e7-82ad-bb9ffbf9b6f0.png)

Is this what you were asking for?

**Comment by RichardLitt** [comment]
Yeah. It doesn't need to be created by jQuery - it should automatically be made by the routes. @VernL are you following this thread? Can you do this in express? 

For now, @Jojokats, using `drawn-and-quarterly.html` for pages you're working on is probably acceptable.

**Comment by Jojokats** [comment]
ok, thanks! I will use `drawn-and-quarterly.html`

I tried contacting @VernL yesterday, but still waiting for a response.

**Comment by Jojokats** [comment]
Just wondering if I should be placing `drawn-and-quarterly.html` in a *Bookstore* directory on in the root.

**Comment by Jojokats** [comment]
I will be creating a PR tonight for drawn-and-quarterly.  I need to fix some details before  pushing it.

**Comment by VernL** [comment]
> @VernL are you following this thread? Can you do this in express?

This will be managed either in express or in the logic for React routing. We will use the page in this PR as a template to create our bookstore component in React.
