### ISSUE TITLE
Import FontAwesome locally using Sass

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#113]
Currently, it is in the `<head>`. See https://github.com/RichardLitt/the-travel-shelf/pull/112#issuecomment-345539636.

**Comment by Jojokats** [comment]
Originally the Font Awesome was linked to the font directory and it worked. I didn't use a CDN.
Sass is only used for styling the font awesome icons once they are imported on the page.

**Comment by RichardLitt** [comment]
Cool. Can you make it work for both your designs and for the main directory, too?

**Comment by Jojokats** [comment]
I will look into it.

**Comment by Jojokats** [comment]
It works yeah!
