### ISSUE TITLE
Please clean root folder

### ISSUE THREAD

**Issue by VernL** [RichardLitt/the-travel-shelf#114]
The root folder is full of files that are not related to the main app. 

This makes working on the main project difficult and could result in unwanted side effects.

The root folder is our React App. 

Please move your code.

**Comment by RichardLitt** [comment]
Can you specify which files you mean, @VernL?

**Comment by VernL** [comment]
/fonts
/img
/js
bookstores.html
index.html
map.js
maps.html

**Comment by RichardLitt** [comment]
Related to https://github.com/RichardLitt/the-travel-shelf/pull/109#issuecomment-345538034

**Comment by VernL** [comment]
Fixed in #117
