### ISSUE TITLE
Add your bio

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#119]
Hey all,
Will requiring your bio for the About page. 
Thanks!

**Comment by RichardLitt** [comment]
Richard:

Richard is an avid bibliophile with a penchant for using words like penchant. He goes to a lot of bookstores, and wanted a place to start them. As a web developer, he figured he could just make a website for that, and so he started this project. He lives in Montréal, although he nomads around too.

Title: Lead

**Comment by Jojokats** [comment]
Hey @RichardLitt , 

Can I add this bio below the first paragraph on the left or do you want it below your image?
Also for your title, should I not add: *Founder, Lead Developer*,  (or Project Manager) just wanted to confirm.
Thanks!

**Comment by RichardLitt** [comment]
below my image. Can you put my image in with the rest of you, though? 

`Founder, Lead Developer` sounds fine. Thanks.

**Comment by Jojokats** [comment]
ok, will move your image with the rest of us :)

**Comment by Jojokats** [comment]
> He goes to a lot of bookstores, and wanted a place to start them

Just wondering if there is a typo, Did you mean **star** them or **start**  them?

**Comment by RichardLitt** [comment]
*write about them.

No idea how that happened.

**Comment by RichardLitt** [comment]
@ZJaf, can you get on this please? Or we will write one for you. :D

**Comment by ZJaf** [comment]
Sure.... Voila, 
Shall I update it in the reactify version?
> Full-stack developer, UX/UI follower, Marketing, Strategy, startups. Love innovative solutions. Always excited to learn more. Enjoying Yoga, swimming, cooking and hanging out with friends.

**Comment by RichardLitt** [comment]
Yep! Just go ahead and open a PR.

**Comment by RichardLitt** [comment]
@colinjnash Add yours! I just added Hanie's.

**Comment by RichardLitt** [comment]
@colinjnash Any word on this?
