### ISSUE TITLE
List three reasons for and against using Python and Django or Flask

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#12]
Go!

**Comment by Jojokats** [comment]
# Advantages for using  Python
+ Easy to learn
+ Python lets you build more functions with fewer lines of code.
+ Python and Django are huge in fintech
+ Python is open-source

# Disadvantages for using Python

+ Not the best for small projects;
+ Heavy and you probably won’t utilize the whole framework; 
+ Monolithic one; 
+ All components get deployed together. 

# Advantages for using  Django
Core Solutions in:
+ Internet of Things
+ Blue chip companies
+ IT giants (NASA, Google and more)
+ FinTech companies in Silicon Valley

## Features & functionalities include:
+ AJAX support;
+ Free API;
+ URL routing;
+ Easy Database Migrations;
+ Open source and available for free online

# Disadvantages for using Django
+ Regex to specify its URL:
+ Django is too monolithic
+ The framework has dedicated itself to backwards compatibility
+  It feels like it has too much software for minor projects

**Comment by VernL** [comment]
# Pro's
- Python is the chosen language of the science community. (Think Nasa!!) 
- Python is consistently ranked among the top 5 most active repositories between Q2/12 and Q4/14 ([Source](http://githut.info/))
- Many successful large scale applications run on Django including Pinterest and Instragram. 
- People say Django is Rapid, easy to learn, Elegant and has a great community. 
 - Batteries included :) 

# Con's
- Lack of backwards compatibility between python 2 & python 3. 
- Although Python itself is easy to learn, Django and Flask may prove challenging. 
- It's not JavaScript. (Like it or not, The web is JavaScript...but for science stuff Python wins)

**Comment by RichardLitt** [comment]
Thanks all!

> It feels like it has too much software for minor projects

I agree with this. It's a huge thing. 

> Although Python itself is easy to learn, Django and Flask may prove challenging.

Also agreed.
