### ISSUE TITLE
Create favicon

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#122]
Create favicon

**Comment by RichardLitt** [comment]
Interesting reading: https://stackoverflow.com/questions/10218178/necessary-to-add-link-tag-for-favicon-ico

**Comment by Jojokats** [comment]
> Interesting reading: https://stackoverflow.com/questions/10218178/necessary-to-add-link-tag-for-favicon-ico

Thanks, will look into it!
I just finished creating it in Sketch.

**Comment by Jojokats** [comment]
Which site do you recommend using for the favicon.
I've found 
[Favicon Generator](https://realfavicongenerator.net/)
or should I just push my own 16x16 - 32x32 - 48x48 png?

**Comment by RichardLitt** [comment]
Sounds like the [FAQ](https://realfavicongenerator.net/faq) can help you there.

**Comment by Jojokats** [comment]
yes, it looks very comprehensive. Thanks!
