### ISSUE TITLE
Create Intro paragraph for the hero image

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#124]
Please write the intro paragraph for the hero image on the index.html page.
Thanks!

**Comment by RichardLitt** [comment]
The hero image on the homepage should be the first bookstore. It should be a short - one sentence description, if that - of the store.

**Comment by RichardLitt** [comment]
Use Drawn and Quarterly, for now. 

> Graphic novels and a keen selection
> Montréal, Québec

That should do it.

**Comment by Jojokats** [comment]
> Use Drawn and Quarterly, for now.
Graphic novels and a keen selection
Montréal, Québec

It's a bit short, can you add maybe one more sentence?

**Comment by RichardLitt** [comment]
Can you show me what it looks like? 

R

**Comment by Jojokats** [comment]
> Can you show me what it looks like?

![hero](https://user-images.githubusercontent.com/10158712/33106808-1a52089e-cf02-11e7-98b0-9acac5b54243.png)

**Comment by RichardLitt** [comment]
I think that's too much text. Can we keep it shorter?

**Comment by Jojokats** [comment]
Yes, it's too much text.

Can you write a short intro paragraph that introduces this website to book lovers/bibliophiles around the world?

Maybe just one sentence. Thanks!

**Comment by RichardLitt** [comment]
> The Travel Shelf is a curated listing of beautiful, independent bookstores around the world.
