### ISSUE TITLE
About page and contact page

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#132]
Hey @RichardLitt sorry for pushing, but can you merge the About page. Let me know if there are any modifications and would be happy to fix them. 
@ZJaf , can work on coding it tomorrow in React.js

I will submit the contact page that's ready afterwards.
Thanks!

**Comment by ZJaf** [comment]
Hey guys, I am working on About page. Right now dealing with css files.

**Comment by RichardLitt** [comment]
Apologies - was AFK for Thanksgiving in the US.
