### ISSUE TITLE
variable $background-dkGrey & img path is incorrect

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#137]
I just ran npm run watch-css in my files.
and there's an error in the About.scss, the variable $background-dkGrey was not updated. but will fix this.

**Comment by Jojokats** [comment]
Image path is incorrect in About.scss, will correct from:
background: url('../img/bs-night-lg-2.jpg') no-repeat 65% 0 fixed;
to
background: url('../../assets/img/About/bs-night-lg-2.jpg') no-repeat 65% 0 fixed;

**Comment by ZJaf** [comment]
>Image path is incorrect in About.scss, will correct from:
background: url('../img/bs-night-lg-2.jpg') no-repeat 65% 0 fixed;
to
background: url('../../assets/img/About/bs-night-lg-2.jpg') no-repeat 65% 0 fixed;


@Jojokats Did you try to run this?! I am getting scope error with that.

**Comment by ZJaf** [comment]
@Jojokats Assign me if you wanted me to take care of it.

**Comment by Jojokats** [comment]
@ZJaf , I took care of it in my last PR
