### ISSUE TITLE
Business Model For the TS

### ISSUE THREAD

**Issue by ZJaf** [RichardLitt/the-travel-shelf#144]
How about formulating one or two slides regarding possible revenue models?
Brainstorm here :)

**Comment by RichardLitt** [comment]
Possible revenue streams:
- Advertising on the site.
- Promoted books from bookstores, which can be ordered through a Stripe API
- A bookstores-pay model where we charge them 2% of any revenue that comes from users who look for books on our site. We would send their searches to independent bookstores near them, who would then be able to respond about the availability of the book at their store, encouraging them to come in and buy them. This could replace Amazon as an easy way to find books nearby in a short period of time.
- A customers-pay model where, for a small fee, we would find and reserve books for them at local bookstores.
- A magazine of the features stories, printed and sold at the bookstores themselves.
- A small press attached to these bookstores, which could sell chapbooks or essays at the stores at a small markup to pay for the site.
- A bookstore-fee for listing.
- Premium features for bookstores or customers.
