### ISSUE TITLE
Front-End: List three reasons for and against using React

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#15]

**Comment by Jojokats** [comment]
# Advantages of using React
1. Virtual DOM in ReactJS makes user experience better and developer’s work faster
2. ReactJS permits reusing code components – significantly saving time
3. An open-source library: constantly developing and open to contributions

# Disadvantages of using React

1. The environment constantly changes
Developers must regularly relearn the new ways of doing things. Everything is evolving, and some developers are not comfortable with keeping up with such a pace.

2. Poor documentation
Different and new libraries like Redux and Reflux are promising to accelerate the work of a library or improve the entire React ecosystem.

3. ‘HTML in my JavaScript!’ 
ReactJS uses JSX, syntax extension, which allows mixing HTML with JavaScript. Developers and designers complain about JSX’s complexity and consequent steep learning curve

**Comment by HanieJ** [comment]
![react](https://qph.ec.quoracdn.net/main-qimg-c40a657d54812f28c1bb06ec1687f6a8.webp)

**Comment by VernL** [comment]
## Pro's
- Very popular (has more stars than any other front-end JS framework on [GitHub](https://github.com/showcases/front-end-javascript-frameworks?s=stars))
 - React Native for IOS and Android development. 
- Specialized at building UI's. (Can be extended to create single page applications.)

## Con's
- Steep learning curve
- Facebook (don't tell **them** I said that...)

*bonus: [Video](https://www.youtube.com/watch?v=JPT3bFIwJYA) introducting React JS with an interesting comparision between ReactJS and Angular 2

**Comment by RichardLitt** [comment]
\o/
