### ISSUE TITLE
Implement OAuth

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#151]
This will include a sign-in page, user settings, etc. 

From #25.

**Comment by VernL** [comment]
[Auth0.com](https://auth0.com/pricing) offer their services for free to open source projects on condition that we add an attribution badge to the site. Thoughts?

**Comment by RichardLitt** [comment]
Just do it. 👍

**Comment by VernL** [comment]
Checkout branch feat/auth for authentication using Auth0. Warning: lots of new code.

Also, checkout it out running on [heroku](https://mysterious-tor-16246.herokuapp.com/)

So we have Auth, what should be do with it?? :D

**Comment by RichardLitt** [comment]
Nice! Well done. 

What would _you_ like to do with it?

**Comment by RichardLitt** [comment]
Closing as not a feature we need ATM.

**Comment by RichardLitt** [comment]
Also a dupe of #47.
