### ISSUE TITLE
Front-End: List three reasons for and against using Vue.js

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#16]

**Comment by hammerhead79** [comment]
# I can see similarities to our project 

[![greensprout](https://user-images.githubusercontent.com/25584914/30649056-910893cc-9ded-11e7-9dba-8ff840e29d93.png)](https://www.greensprout.co/)

## [Here's a good review about Vue.js that created greensprout](https://imju.me/vue-js-for-newbies-63601828a9fe)

![screen shot 2017-09-20 at 10 32 04 am](https://user-images.githubusercontent.com/25584914/30649743-15b7ab70-9def-11e7-8c13-cb5b275e5fa2.png)
![screen shot 2017-09-20 at 10 32 19 am](https://user-images.githubusercontent.com/25584914/30649747-17813714-9def-11e7-9947-0e2da1ea4e52.png)

**Comment by RichardLitt** [comment]
This is almost a year old. Can we find a newer resource? Does this all still apply? :)

**Comment by VernL** [comment]
_**Disclaimer**:_ I <3 Vue.js 
## Pro's
- Works well for projects of all sizes, from creating simple widgets that may be added to existing websites all the way to enterprise level applications. 
- Relatively easy to learn and enjoyable to use. (All you need is HTML and ES5 JS) 
- Creates responsive and beautiful single page web-apps.
- GREAT docs (including the most unbiased comparison between other front end frameworks found [here](https://vuejs.org/v2/guide/comparison.html))
- It's fun and intuitive.

## Con's
- Not as popular as React. (I've yet to find anybody else who uses vuejs in Montreal)
- Vue.js is not a sought after skill in the local job market.

**Comment by Jojokats** [comment]
# Pros
+ Ember makes a great choice for writing web apps. Many ambitious apps are built using the framework. It has been particularly well received by the Ruby community.
+ In many cases Vue.js is replacing Angular. It is a lightweight library with two way data binding and virtual DOM that doesn’t confuse you with tons of things and helps you with just what you need to develop a web app.
+ The recent version 2 release is lightweight and makes Vue perform faster than both React and Angular.

# Cons 
+  A closed community development
Unlike other frameworks, Vue doesn’t yet have the widespread support of its fellow frameworks as it is not as popular as React or Angular 2 & 4. There are far more resources for React.js than Vue.js.

+ Not many job demands

**Comment by hammerhead79** [comment]
![vuejs](https://user-images.githubusercontent.com/25584914/30666765-66e5f090-9e23-11e7-86b0-a038c839700c.png)

**Comment by RichardLitt** [comment]
> Vue.js is not a sought after skill in the local job market.

This is a huge issue. I think while it may be useful later, you're more likely to be using React in a few months.
