### ISSUE TITLE
Implement card

### ISSUE THREAD

**Issue by VernL** [RichardLitt/the-travel-shelf#178]
Implement card on store page

**Comment by RichardLitt** [comment]
There is already a card. What is needed is a new card prop; at the moment, there are some issues with the card - rounded corners beneath the image, a lack of hover-state on the button, and so on. A card library _should_ be a faster way to implement cards. 

This issue can take a backseat while we get more cards. This may just need some small tweaking.

**Comment by RichardLitt** [comment]
I believe this is done. Thank you!
