### ISSUE TITLE
Implement D3 MAP

### ISSUE THREAD

**Issue by VernL** [RichardLitt/the-travel-shelf#180]
Implement D3 map.

- Green icon for bookstores with reviews
- Grey icons for other bookstores.

**Comment by RichardLitt** [comment]
This will be for Montréal first. It'll need to be it's own component. Also, see how easy it would be to add other cities.

**Comment by VernL** [comment]
I added a basic map of Montreal. I will continue to work on it to make it mobile friendly and add zoom/pan functionality. 

In theory, adding additional cities is not difficult. The challenge is providing a good user experience when navigating a map covering large areas. 

For now, I suggest adding a drop down allowing the user to select/render a map of a different city. We can look at globes/world maps etc. in the future.

**Comment by RichardLitt** [comment]
@VernL I think this is done. Why don't you split your future concerns into new issues?
