### ISSUE TITLE
Images for Drawn and Quarterly

### ISSUE THREAD

**Issue by VernL** [RichardLitt/the-travel-shelf#190]
Could we please upload the images somewhere. 

https://drive.google.com/drive/u/0/folders/0B3D8NpRnJZnHY21ubTJHOXZGTGM is available if needed.

**Comment by RichardLitt** [comment]
Just throw them in an `src` folder, for now? We can use a subset - no need to put them all in there.

**Comment by VernL** [comment]
Where can I find the images?

**Comment by RichardLitt** [comment]
Here! https://drive.google.com/drive/folders/0BwWvJqjC4Sdffm9tdnFyeVhxbUFmdS1OWDMzeXNiR1J3NDdMU011al9ISXJuU183U3l6ckU?usp=sharing

**Comment by VernL** [comment]
wow, nice pics!
