### ISSUE TITLE
List three reasons for and against using Elixir

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#20]
This is a backend framework. Why should we use it? Why not? 

https://elixir-lang.org/

**Comment by HanieJ** [comment]
##### tough one! seemed like a perfect lang! ![sigh](http://rs250.pbsrc.com/albums/gg259/raiko-chan/graphics/icon/1b38f9e2.gif~c200)

# Pros:
* Concurrency
* Functional
* Standing on the shoulders of Erlang
* and so on!

# Cons:
* Computational speed may be lower with heavy math
* Not designed for parallel computing, but for fault-tolerance
* Not enough tutorials for learning it deeper

**Comment by Jojokats** [comment]
# Advantages
+ #### The Phoenix Web Framework
The phoenix framework is clearly heavily influenced by Ruby on Rails and coding a Phoenix Web Application feels a lot like coding a Rails app.
Phoenix is such a Railsy solution you’ll feel like you’re building a Rails app, with the exception being that it runs with Elixir and has all the benefits of Elixir and the Erlang virtual machine.
+ #### Speed!
 It’s fast as lightning
+ #### The Erlang Virtual Machine
Elixir runs on the Erlang virtual machine and embraces most of the values of the Erlang community. Both Elixir and Erlang pride themselves for an emphasis on functional programming that are fault-tolerant and highly scalable. 

# Disadvantages
+ #### Elixir is still a very young language. 
This is less severe by the fact that it lives on a very mature and established runtime, but there’s still a high chance that the language itself may evolve in ways that will require you to make changes (large and small) to existing codebases to keep up.

# You can’t really get around learning Erlang. 
+ #### When you build applications with Elixir, you build applications that live on the Erlang ecosystem and runtime. With time, you will have to get to know Erlang, too, if you want to use the whole package efficiently. 

# There’s not a lot of demand for Elixir on the job market so far. 
+ #### This, of course, is something that may change in the future, but I would bet against it ever becoming as big as Ruby on Rails did. Ruby on Rails solved a very clearly defined problem everybody was having;

**Comment by RichardLitt** [comment]
I think the disadvantages outweigh the benefits. We need tutorials, we want to be good on the job market, and we don't want to have to learn Erlang _on top of_ a few other languages like JavaScript. I suggest we close this issue, and stop considering Elixir. 

React to this: thumbs up means you agree, thumbs down means disagree, and another comment means let's continue discussion.
