### ISSUE TITLE
Image not loading in Stores card

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#211]
<img width="1165" alt="screen shot 2018-01-18 at 12 44 07 pm" src="https://user-images.githubusercontent.com/910753/35118061-a69dea64-fc5e-11e7-9cd1-d6619463bff6.png">

Replicated by another person. However, I can't replicate locally.

**Comment by VernL** [comment]
- The [docs](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#using-the-public-folder) indicate that the correct way to load images is by using an import statement. 

- I am not sure how to do this as the image urls are coming from the database. 

- I have implemented a solution in PR #214 using the public folder that should resolve the issue.

**Comment by VernL** [comment]
- The proposed solution did not work...
- The problem does not show up locally, but on heroku images dq_1 & dq_2 are blank.

**Comment by VernL** [comment]
![image](https://user-images.githubusercontent.com/20936512/35157301-92660542-fd01-11e7-8451-d571c1884511.png)

**Comment by VernL** [comment]
This has been bothering me as It shouldn't be too difficult to display images! I implemented a solution in branch fix/imageLoading.  It did require a little restructuring but it seems to work by letting webpack manage the images. I will PR after #217. In the meantime, images are broken :'(
