### ISSUE TITLE
port site to gastbyjs

### ISSUE THREAD

**Issue by VernL** [RichardLitt/the-travel-shelf#235]
Hi all,

The site is currently very complex as it uses with redux etc. This makes implementing new features difficult and could discourage others from participating in the project. 

I propose we rebuild the site using [gatsby](https://www.gatsbyjs.org/). Gatsby is built on react so a lot of our code will be reusable. We could also integrate with [netlifycms](https://www.netlifycms.org/) and host on netlify. This would greatly improve the usability of the site and could be a great chance for everyone to learn gastby :D 

- This could solve #219, #202, #215, #183 and possibly #152. 

Thoughts?

**Comment by RichardLitt** [comment]
I think this sounds good to me! Redux is definitely overkill, and it would be great to be able to use netlifycms, as that would enable us to more easily edit things. 

Go for it.

**Comment by VernL** [comment]
This is mostly done. The repo is available [here](https://github.com/VernL/p-gatsby-the-travel-shelf)

Preview the site [here](https://sharp-bose-ab73ce.netlify.com/)

**Comment by VernL** [comment]
I feel this is complete. Closing the issue. Feel free to comment.

**Comment by RichardLitt** [comment]
@VernL Was this merged?

**Comment by RichardLitt** [comment]
Ok - should we merge that repo into this one?

**Comment by RichardLitt** [comment]
@VernL This looks good! Why don't you copy over the files to this repo in a PR. Thanks.
