### ISSUE TITLE
Find out what version of React to use

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#26]
There are a lot of different options beyond "using React."

I want us to learn this:
- What is React?
- What is Redux?
- What is Flux?
- What is Preact

What other frameworks are related and work on top of React, that we should think of?

**Comment by VernL** [comment]
**React** is JavaScript library for building user interfaces. One of the benefits is that React presents a declarative view of how the page should look allowing it to be predictable and efficient at rendering dynamic content. It works by tracking changes in a Virtual DOM and generating/applying declarations to the actual DOM to reflect these changes.  
**Redux** is a predictable state container for JavaScript apps. 
**Flux** is a design pattern to manage state using __unidirectional__ data flows :D. Redux follows these principals...It's an alternative to the standard MVC design patterns and was developed to resolve scalability and predictability issues. There is an awesome talk (40 minutes) on the [flux website](http://facebook.github.io/flux/) that really explains everything well. 
**Preact** is a striped down version of react. It's main focus is Virtual DOM abstraction. 

We will need to use React-router for routing.

**Comment by RichardLitt** [comment]
It sounds like we may be able to get away with Preact. What do you think?

**Comment by VernL** [comment]
Yes, I think we can use Preact, take advantage of the performance boost and use[ preact-compact](https://github.com/developit/preact-compat) to work with React-based modules.

**Comment by RichardLitt** [comment]
Thought about it some more. I think we should just go with vanilla React, for now. We can switch to preact later as needed. This will help us by being a bit more mainstream.
