### ISSUE TITLE
Designs: HTML or Sketch or Photoshop or Illustrator

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#27]
I want us to have some designs drawn up for this project, _before we start coding_. This is related to #25. 

For this, I need to know - what program should we draw prototypes and wireframes in? 

Normally, I use HTML and CSS directly. But I've heard Sketch and Photoshop and Illustrator are also good. What do you think? What are the benefits of one verse the other?

**Comment by HanieJ** [comment]
They have different applications! so the question is that what we want to do exactly!
Wireframing:
https://wireframe.cc/
or 
https://www.invisionapp.com/
I prefer wireframe(been respected and used in software development projects)

Photoshop: photo editor! (I used it for everything except that though :D)
Illustrator: design tool (logo, biz card,etc.)

Sketch,![Macaw](macaw.co), Dreamweaver: Web Design tools( I've heard the codes which are generated by these applications are not easy to read/well organized. That is why they are not recommended for web development. Though (when I was young) I used Dreamweaver and I had really no trouble with HTML or CSS.

Directly CSS,HTML? :( I really have a hard time with CSS! what about Sass?

**Comment by VernL** [comment]
wireframe.cc looks cool!.

I was recommended _[balsamiq markup](https://balsamiq.com/)_ and really like it. It's very similar to wireframe.cc but with more features. 

Check out [this](https://the-travel-shelf.mybalsamiq.com/projects/the-travel-shelf/prototype/the-travel-shelf_Landing?key=981a312c7dd6a29c602ec4a66689d35ad3c89e12) beautiful concept for our landing page! Pretty awesome....

Also, it's $12 a month for unlimited users compared to $12 a month.ish per person for invision. 

Photoshop is maybe overkill for wire-framing and more appropriate for creating assets?? 

I like the idea of creating prototypes and wireframes before jumping into HTML/CSS, but either way is fine with me.

**Comment by VernL** [comment]
If anybody want to give it a try, ping me your e-mail address on slack and I'll invite

**Comment by HanieJ** [comment]
I'm in : me@hjafari.com

**Comment by Jojokats** [comment]
I am comfortable using Sketch

**Comment by RichardLitt** [comment]
I've heard good things about Balsamiq, too. 

@HanieJ Yes, Sass is much better. Less is also an option. :) 

It sounds like we need to finish up #25 before we can really get into this one.

**Comment by VernL** [comment]
>For prototyping, we can use inVision
Both invision and wireframe.cc premium are $10+ per person per month. 
Balsamiq seems similar but $10ish for 3 project with unlimited users. It gets my vote

**Comment by RichardLitt** [comment]
> I think we should start by hand drawing sketches of each page

I agree with this. @Jojokats - do you think we should all draw up some wireframes for next week?

**Comment by ZJaf** [comment]
I can do the full bookstore page with bootstrap by next week. Instead of wireframe it! but no doubt that wireframing is a good idea!

**Comment by RichardLitt** [comment]
>I can do the full bookstore page with bootstrap by next week. Instead of wireframe it! but no doubt that wireframing is a good idea!

The wireframes will inform our design. Let's wait until we have some before building out with bootstrap.

**Comment by hammerhead79** [comment]
## Sample Mockup
![the travel shelf - page 1](https://user-images.githubusercontent.com/25584914/31197445-243022be-a91f-11e7-8dac-95e184b0f6e1.jpeg)

**Comment by ZJaf** [comment]
I have the bookstore page :smile:
thanks to @VernL 's Balsamiq
![bookstore-page](https://user-images.githubusercontent.com/30536467/31256764-84a33350-aa02-11e7-844d-ab48b79c6fb2.png)

**Comment by RichardLitt** [comment]
It looks like we're going with HTML mockups, from @Jojokats.
