### ISSUE TITLE
Build a node app

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#28]
Show me a GitHub repository where when I run `node app.js` and go to localhost:4000 in my browser, I will see `hello world!`. You should be able to do this after doing the javascriping and learnyounode on https://nodeschool.io/#workshoppers.

**Comment by Jojokats** [comment]
I built today my node app.js and when you go to [localhost:4000](http://localhost:4000/) you can see my `Hello World!` you can find my [repo here](https://github.com/Jojokats/node-app)

**Comment by RichardLitt** [comment]
How's this going, ya'll?

**Comment by VernL** [comment]
JUGGLING ASYNC (Exercise 9 of 13) killed my family and pillaged my village...

**Comment by hammerhead79** [comment]
I was learning git and GitHub but will work onto learning node.js right now.

**Comment by ZJaf** [comment]
Here is my code:
var express = require('express');
var app = express();

app.get('/', function(req, res) {
    res.send('hello world');
});

app.listen(3000);

**Comment by RichardLitt** [comment]
Thanks @ZJaf! It doesn't _need_ a GitHub repository, but in order for me to run it, I'll need to get the code, and in a file. That would necessitate a repo. :) 

But https://github.com/ZJaf/NodePractice/tree/master looks good enough. :D

**Comment by ZJaf** [comment]
@RichardLitt  shall I close this issue!

**Comment by RichardLitt** [comment]
@ZJaf Looks like we've all done some version of this, so, yep. :)
