### ISSUE TITLE
Meeting Notes

### ISSUE THREAD

**Issue by VernL** [RichardLitt/the-travel-shelf#29]
Hi all,
I added notes from our last meeting to the project. (next time I'll add them with a pull request, had a little mixup :) 
The objective is to create a clear and concise record of our discussions. I'd appreciate if everyone skimmed through these and commented if anything should be added or changed.
Cheers,

**Comment by RichardLitt** [comment]
> (next time I'll add them with a pull request, had a little mixup :)

Sounds good. :) 

Thanks @VernL!
