### ISSUE TITLE
Add an index.js file

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#30]
Can someone PR an index file that says "Hello world"?

**Comment by RichardLitt** [comment]
https://guides.github.com/activities/forking/

**Comment by hammerhead79** [comment]
done. Thanks! for your help.

**Comment by ZJaf** [comment]
@RichardLitt what is PR stand for?

**Comment by ZJaf** [comment]
My index.js is working fine. I used express to say hi on localhost.  but I am not sure if this is normal:
git commit -m "say hello with index.js"
[kitty b9a0ed4] say hello with index.js
 322 files changed, 52101 insertions(+), 1 deletion(-)
 

Are you ok with me to push these all up?

**Comment by RichardLitt** [comment]
@ZJaf Sounds good! 

```
$ git commit -m "say hello with index.js"
[kitty b9a0ed4] say hello with index.js
322 files changed, 52101 insertions(+), 1 deletion(-)
```

Normally, we put code in backticks, as it makes the formatting easier. Also, including a prompt is good - in this case, the normal one is either a `$` or a `>` for a shell command. 

The output you're seeing is the normal git output when you've done something right. However - it is a bit worrying - what 322 files have changed? Can you show me what files were changed in the b9a0ed4 commit? 

For now, don't push to the `master` branch. You can always push to another branch (you can make one with `git checkout -b new-branch`, and then open a Pull Request to `master` showing the diffs. 

Let me know if any of this explanation is confusing! Ask questions, and I'll point you to a resource.
