### ISSUE TITLE
Add a package.json

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#31]
Make sure it's marked as `private`. This should be a field in the package.json.  

Learn about `npm init --yes`. Put a link here.

**Comment by RichardLitt** [comment]
Note: Do this in a PR.

**Comment by VernL** [comment]
Everything about package.json files is [here](https://docs.npmjs.com/files/package.json)
`npm init --yes` creates a package.json file with default values skipping the prompts. More info [here](https://docs.npmjs.com/cli/init).

**Comment by ZJaf** [comment]
The question is that if Vernon is committing json package to the master branch, then we do not need to add ours?! We just comment on it? 
When am I supposed to pull those changes to mine?

**Comment by Jojokats** [comment]
I just uploaded files to the homepage branch which include a package.json

**Comment by RichardLitt** [comment]
> The question is that if Vernon is committing json package to the master branch, then we do not need to add ours?!

You're right, only one is needed in the main branch. However, multiple people can open a PR. This exercise is largely to help you all get better at opening PRs and submitting changes. I'll only merge the first one in - the other pull requests won't be used. 

> We just comment on it?

Sure! Comment on anyone else's PRs. That's how we do review. 

> When am I supposed to pull those changes to mine?

When it has been merged into master, generally. 

> @Jojokats: I just uploaded files to the homepage branch which include a package.json

Great! It's good practice to reference the issue that the PR is related to in the PR, so that there is a back reference here. Can you edit the PR to reference this issue? https://help.github.com/articles/autolinked-references-and-urls/

**Comment by RichardLitt** [comment]
@VernL Same goes for you - can you reference this issue from your relevant PR?
