### ISSUE TITLE
Add an index.html with a blue background

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#32]
Let's get our first page up! Assigning you two to get started - you can both PR it, and I can merge one of them.

**Comment by RichardLitt** [comment]
If you have any questions, please ping me!

**Comment by Jojokats** [comment]
Before we can do anything, we should agree on a wireframe & an idea of content would be helpful but mostly a wireframe.

**Comment by RichardLitt** [comment]
> Before we can do anything, we should agree on a wireframe & an idea of content would be helpful but mostly a wireframe.

That's a valid point most of the time. But here, I'm not asking for you to make a design which will last forever - rather, I want the index.html file to exist so that we can start working on the views. This is unrelated to the final design; it's an architectural change that's needed.

**Comment by Jojokats** [comment]
Ok, will work on it!

**Comment by ZJaf** [comment]
@RichardLitt index.html?

**Comment by Jojokats** [comment]
I just uploaded the index.html with a quick navbar and hero section on the homepage branch to get us started as requested.

**Comment by Jojokats** [comment]
I also included an image for the hero and made a quick logo to start the website

**Comment by ZJaf** [comment]
I feel I am just gonna repeat what Joanna is doing :hahaha:

**Comment by RichardLitt** [comment]
> I feel I am just gonna repeat what Joanna is doing :hahaha: 

Totally OK. 

> I just uploaded the index.html with a quick navbar and hero section on the homepage branch to get us started as requested.

Thanks! Can you reference this issue in that pull request? There should be backlinks, so that, in the future, you don't need to go into this thread to say you've done it - we'll know immediately.

**Comment by Jojokats** [comment]
>Thanks! Can you reference this issue in that pull request? There should be backlinks, so that, in the future, you don't need to go into this thread to say you've done it - we'll know immediately.

I don't know how to do this... sorry

**Comment by RichardLitt** [comment]
Take a look at this: https://help.github.com/articles/autolinked-references-and-urls/. Drop a link to this issue in the relevant pull request in a comment. :)

**Comment by Jojokats** [comment]
I'm having issues with pushing the changes. I changed the name from app to Base but after doing a git status, it's showing me in red that everything is deleted.
If you can have a look and let me know what to do. Thanks

![git-m](https://user-images.githubusercontent.com/10158712/31182626-64474a44-a8f2-11e7-947c-8e44415c92e7.png)

**Comment by RichardLitt** [comment]
What does it say in 'Untracked files'? It looks like there is more to this commit. Can you give me the full command, too? 

You should be able to copy and paste all of the output here in a code block.

**Comment by Jojokats** [comment]
```
git status
On branch homepage
Your branch is up-to-date with 'origin/homepage'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    ../app/.DS_Store
	deleted:    ../app/.gitignore
	deleted:    ../app/README.md
	deleted:    ../app/gulpfile.js
	deleted:    ../app/npm-debug.log
	deleted:    ../app/package.json
	deleted:    ../app/src/.DS_Store
	deleted:    ../app/src/css/bootstrap.css
	deleted:    ../app/src/css/font-awesome.min.css
	deleted:    ../app/src/css/style.css
	deleted:    ../app/src/fonts/FontAwesome.otf
	deleted:    ../app/src/fonts/fontawesome-webfont.eot
	deleted:    ../app/src/fonts/fontawesome-webfont.svg
	deleted:    ../app/src/fonts/fontawesome-webfont.ttf
	deleted:    ../app/src/fonts/fontawesome-webfont.woff
	deleted:    ../app/src/fonts/fontawesome-webfont.woff2
	deleted:    ../app/src/img/annie.jpg
	deleted:    ../app/src/img/ts-logo.jpg
	deleted:    ../app/src/img/ts-logo.svg
	deleted:    ../app/src/img/ts-logo@2x.jpg
	deleted:    ../app/src/img/ts-logo@3x.jpg
	deleted:    ../app/src/index.html
	deleted:    ../app/src/js/bootstrap.min.js
	deleted:    ../app/src/js/jquery.min.js
	deleted:    ../app/src/js/navbar-fixed.js
	deleted:    ../app/src/js/popper.min.js
	deleted:    ../app/src/scss/style.scss

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../.DS_Store
	./
	../npm-debug.log
	../travel-shelf.sketch

no changes added to commit (use "git add" and/or "git commit -a")
Joannas-MacBook-Pro:app joannakatsifaraki$ 

```

**Comment by RichardLitt** [comment]
Also, I think that this comment is actually more relevant to #36, not to this issue. #36 is your implementation. It's generally a good idea to put comments as close to the code as possible.

**Comment by Jojokats** [comment]
OK, wasn't sure , will move it

**Comment by RichardLitt** [comment]
Don't worry about moving it- it's OK.

**Comment by RichardLitt** [comment]
Did you move those files somewhere else? What does `ls` show you?

**Comment by Jojokats** [comment]
```
Joannas-MacBook-Pro:app joannakatsifaraki$ ls
README.md     gulpfile.js   node_modules  npm-debug.log package.json  src
Joannas-MacBook-Pro:app joannakatsifaraki$ ls -al
total 56
drwxr-xr-x   10 joannakatsifaraki  staff    340  3 Oct 20:33 .
drwxr-xr-x   12 joannakatsifaraki  staff    408  4 Oct 10:05 ..
-rw-r--r--@   1 joannakatsifaraki  staff   6148  3 Oct 20:33 .DS_Store
-rw-r--r--    1 joannakatsifaraki  staff     37  4 Oct 09:54 .gitignore
-rw-r--r--    1 joannakatsifaraki  staff    275  3 Oct 16:26 README.md
-rw-r--r--    1 joannakatsifaraki  staff   1301 11 Sep 20:48 gulpfile.js
drwxr-xr-x  413 joannakatsifaraki  staff  14042  3 Oct 18:11 node_modules
-rw-r--r--    1 joannakatsifaraki  staff   2841  3 Oct 18:16 npm-debug.log
-rw-r--r--    1 joannakatsifaraki  staff    451 11 Sep 21:16 package.json
drwxr-xr-x    9 joannakatsifaraki  staff    306  3 Oct 20:33 src
Joannas-MacBook-Pro:app joannakatsifaraki$ 


```

**Comment by RichardLitt** [comment]
Show me the output of `git log`. It looks like you've already moved the files and committed them, but didn't delete `app` yet. Is that right?

**Comment by Jojokats** [comment]
>Did you move those files somewhere else?

Yes at #36 should I delete them there?

**Comment by Jojokats** [comment]
I changed the name of app to Base in Finder

**Comment by Jojokats** [comment]
```
Joannas-MacBook-Pro:app joannakatsifaraki$ git log
commit 86d51c615d921ee48f8444534bbbf3c302583bb9 (HEAD -> homepage, origin/homepage)
Author: Joanna <morningstarjk@hotmail.com>
Date:   Tue Oct 3 21:41:07 2017 -0400

    Added navbar and Hero section

commit 054b33a8b9108b3c0528ac60218218de0e586459
Merge: 1aef947 4c63745
Author: Joanna <morningstarjk@hotmail.com>
Date:   Tue Oct 3 16:26:27 2017 -0400

    Merge branch 'homepage' of https://github.com/RichardLitt/the-travel-shelf into homepage

commit 1aef947e897adf08af1402197d0d5b6d1a6046d0
Author: Joanna <morningstarjk@hotmail.com>
Date:   Tue Oct 3 16:25:24 2017 -0400

    Test changes in index.html

commit 4c63745437d23ac22698d21203851880af8cec96
Author: Joanna Katsifaraki <morningstarjk@hotmail.com>
Date:   Tue Oct 3 16:16:08 2017 -0400

    Update README.md

commit ec25df8e0c19ecdff4efdf2780619977a5844f0c
Author: Joanna <morningstarjk@hotmail.com>
Date:   Tue Oct 3 16:13:03 2017 -0400

    Initial commit
:

```

**Comment by RichardLitt** [comment]
> I changed the name of app to Base in Finder

Why to `base`? I meant you could move all of the app folders to the root directory for this repository - there's no need to put stuff in an extra folder. 

Why don't I see `Base` when you ran `ls`?

**Comment by Jojokats** [comment]
OK, misunderstood.
I changed the name back to app and did a git status:
```
Joannas-MacBook-Pro:app joannakatsifaraki$ ls
README.md     gulpfile.js   node_modules  npm-debug.log package.json  src
Joannas-MacBook-Pro:app joannakatsifaraki$ git status
On branch homepage
Your branch is up-to-date with 'origin/homepage'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../.DS_Store
	../npm-debug.log
	../travel-shelf.sketch

no changes added to commit (use "git add" and/or "git commit -a")
Joannas-MacBook-Pro:app joannakatsifaraki$ 

```

**Comment by Jojokats** [comment]
so is this safe? Can I 
git add .
without breaking anything lol

**Comment by RichardLitt** [comment]
Well, first, `rm .DS_Store` and `rm npm-debug.log`. You don't need those. 

What does `git diff` show?

**Comment by Jojokats** [comment]
I placed them in .gitignore but it's not working!

```
Joannas-MacBook-Pro:app joannakatsifaraki$ git status
On branch homepage
Your branch is up-to-date with 'origin/homepage'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../.DS_Store
	../npm-debug.log
	../travel-shelf.sketch

no changes added to commit (use "git add" and/or "git commit -a")
Joannas-MacBook-Pro:app joannakatsifaraki$ git diff
diff --git a/app/.gitignore b/app/.gitignore
index 6db4ce0..825fc67 100644
--- a/app/.gitignore
+++ b/app/.gitignore
@@ -1,2 +1,3 @@
 node_modules
-DS_Store
+.DS_Store

```

**Comment by Jojokats** [comment]
Do you want me to move index.html in the base / root of app folder?

**Comment by RichardLitt** [comment]
It doesn't work because they're still checked into git. Try removing them; if not, commiting them; if necessary, you could also try squashing commits (that will be fun and interesting!)

Yes, move all of the things in app/ into the base folder,  `/`.

**Comment by Jojokats** [comment]
OK, problem again, I moved everything out of src folder and deleted src folder. But I'm getting the message that everything is deleted again when I do git status:
```
Joannas-MacBook-Pro:app joannakatsifaraki$ git status
On branch homepage
Your branch is up-to-date with 'origin/homepage'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .DS_Store
	modified:   .gitignore
	deleted:    src/.DS_Store
	deleted:    src/css/bootstrap.css
	deleted:    src/css/font-awesome.min.css
	deleted:    src/css/style.css
	deleted:    src/fonts/FontAwesome.otf
	deleted:    src/fonts/fontawesome-webfont.eot
	deleted:    src/fonts/fontawesome-webfont.svg
	deleted:    src/fonts/fontawesome-webfont.ttf
	deleted:    src/fonts/fontawesome-webfont.woff
	deleted:    src/fonts/fontawesome-webfont.woff2
	deleted:    src/img/annie.jpg
	deleted:    src/img/ts-logo.jpg
	deleted:    src/img/ts-logo.svg
	deleted:    src/img/ts-logo@2x.jpg
	deleted:    src/img/ts-logo@3x.jpg
	deleted:    src/index.html
	deleted:    src/js/bootstrap.min.js
	deleted:    src/js/jquery.min.js
	deleted:    src/js/navbar-fixed.js
	deleted:    src/js/popper.min.js
	deleted:    src/scss/style.scss

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../.DS_Store
	css/
	fonts/
	img/
	index.html
	js/
	scss/
	../npm-debug.log
	../travel-shelf.sketch

no changes added to commit (use "git add" and/or "git commit -a")
Joannas-MacBook-Pro:app joannakatsifaraki$ 
```

**Comment by Jojokats** [comment]
So, I feel like just deleting this repo  and starting from scratch.....

**Comment by Jojokats** [comment]
> Thanks! Can you reference this issue in that pull request? There should be backlinks, so that, in the future, you don't need to go into this thread to say you've done it - we'll know immediately.
Done!

**Comment by RichardLitt** [comment]
> Done!

Can you point to where you did this? I don't see a reference here, so I am not sure that this is done. 

Try adding the untracked files that used to be in app to the git index. You should see a different note than deleted. Do you?

**Comment by Jojokats** [comment]
I referenced it in one of my messages here @ #32 but don't know how to reference the specific message.

**Comment by Jojokats** [comment]
I just uploaded the index.html with a quick navbar and hero section on the homepage branch to get us started as requested #36

**Comment by Jojokats** [comment]
> Try adding the untracked files that used to be in app to the git index. You should see a different note than deleted. Do you?

What command do I use, sorry, newbie here!

**Comment by RichardLitt** [comment]
I just referenced it. See the reference, above? 

> Try adding the untracked files that used to be in app to the git index. You should see a different note than deleted. Do you?

Let's keep this conversation in #36. Try `git add`.
