### ISSUE TITLE
Add a routing file that uses express

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#38]
It's possible we can use a starter template for this, too. See what looks good to you?

**Comment by VernL** [comment]
I would approach this issue using the express application generator. 
The routing files is created, along with the skeleton for the project. 
See #39

**Comment by VernL** [comment]
As we are gearing toward an express app with reactive components, should we consider using the workflow as described in [this](https://daveceddia.com/create-react-app-express-backend/) article?

**Comment by RichardLitt** [comment]
Sweet. That's a good question. @ZJaf what do you think? 

on an unrelated noted, @VernL, maybe you can help me out. Is yarn still good to learn, with npm@5's improvements? Should I switch?

**Comment by ZJaf** [comment]
I take time to look at it this weekend. I will get back asap!

**Comment by VernL** [comment]
> on an unrelated noted, @VernL, maybe you can help me out. Is yarn still good to learn, with npm@5's improvements? Should I switch?

Besides yarn being harder to search for (unless you are into knitting), I believe this quote may help answer your question:
 > With npm@5, npm is back in the race with Yarn. There is no more a pronounced difference between the two.
> __I see no reason why if you’re on Yarn to switch to npm or vice versa, as long as you update to v5.__
>There is effectively no difference the two anymore, except for the minor difference in performance where Yarn holds a slim lead.
[source](https://medium.com/@nikjohn/npm-5-yarn-killer-ba69737b24d0)

npm@5 basically responded to every competitive advantage yarn had with the release of npm@5.
In particular, the addition of a package-lock-json file, resolves potential versioning issues that where present in npm's previous releases. 

If I had to choose between the two, I would currently learn npm as it is the default package manager for Node.js, and I don't personally believe a slight performance improvement is enough incentive to switch from the norm. 

Does this answer your question??

**Comment by RichardLitt** [comment]
Very much so. That's what I thought. Thank you! I use npm exclusively, and never actually switched to yarn. Good to know I don't have to.

**Comment by ZJaf** [comment]
After having the workshop with React, I do agree using the approach of  ``npm install -g express-generator `` seems to be a good idea. It will simplify lots of processes and make a good foundation.
