### ISSUE TITLE
Set git authentication

### ISSUE THREAD

**Issue by HanieJ** [RichardLitt/the-travel-shelf#4]

**Comment by HanieJ** [comment]
I found this article.
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
I generated a key and connect my account to it.

**Comment by RichardLitt** [comment]
Great! Want to go ahead and close this issue, if it is solve?

**Comment by RichardLitt** [comment]
@HanieJ ping

**Comment by HanieJ** [comment]
Yes! Let's close it!
