### ISSUE TITLE
Review nvie's git branching model

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#42]
This is a great workflow to follow when making branches. I've come back to this article often over the years. 

http://nvie.com/posts/a-successful-git-branching-model/

Leave a comment or reaction if you've read it.

**Comment by VernL** [comment]
Very informative. Keeping this beauty as a reference.

**Comment by ZJaf** [comment]
It is exactly addressing the questions I had the other day Richard! Thanks for sharing!

**Comment by RichardLitt** [comment]
We don't need to have a develop branch at the moment - but branching off of master and using feature branches is the smart(tm) thing to do :)

**Comment by Jojokats** [comment]
Looks like an awesome article. Thanks for sharing!
