### ISSUE TITLE
Using create-react-app 

### ISSUE THREAD

**Issue by ZJaf** [RichardLitt/the-travel-shelf#44]
Shall we install this package to use React and use its setup as our basic setup?

**Comment by ZJaf** [comment]
I can! but this will create lots of folders, make changes to the JSON and so on! Are you fine with it?

**Comment by VernL** [comment]
Before we travel down this route, I would like to re-open the discussion of moving straight to a React-app. I am open and exited to use React on a project, however, as this will be the first project for many members on our team, I wonder if it could be beneficial to create our MVP as a node/express app. Once we have something up and running, we could refactor with React. I feel this is an important issue for the project and am interested to hear everyone's thoughts before we commit and move straight to React.

What do you guys think?

**Comment by Jojokats** [comment]
Thanks for asking @VernL! Sounds good to me !

**Comment by VernL** [comment]
A little context, I went to the JS Montreal last night and this discussion was help later in the evening around the beer table. The main issue was identified as jumping into React without a solid understanding of what problems the framework solves. 

Could we add some pro's and con's?
- Pro:
   - React exists to create single page applications. This is exactly what we are building and is well suited for the job!
  - We could learn the tools being used by the pros and quickly become "job ready"
- Con:
   - Using React without a solid understanding of the fundamentals, could lead to a poor understanding of what React is actually doing. This could push newcomers to view everything as "syntax" and encourage them to simply copy and past code snippets without a proper understanding of what they are actually doing.

**Comment by RichardLitt** [comment]
Refactoring sounds smarter, to me. 

> React exists to create single page applications. This is exactly what we are building and is well suited for the job!

We don't have to build an SPA. 

> We could learn the tools being used by the pros and quickly become "job ready"

Sure, but we could also learn them more efficiently. 

> Using React without a solid understanding of the fundamentals, could lead to a poor understanding of what React is actually doing. 

Happened to me with Angular. 

> Using Node/express will require the entire page to be re-rendered anytime an element on the page needs to be updated.

Not really a con for this project, I think.

Let's go with Node & Express for now?

**Comment by VernL** [comment]
I'm sold on Node & Express. 

Anyone have an opinion on templating language? 

I typically use EJS as it uses standard HTML tags but I believe jade/pug is the most popular. 

What does everyone think?

**Comment by RichardLitt** [comment]
EJS works for me.

**Comment by Jojokats** [comment]
EJS is good for me as well.

**Comment by ZJaf** [comment]
I talked to Vernon regarding the refactoring. I think it will be time-consuming but at the same time, I am learning to react and I see we need a better foundation to work on it. I agree with Node & express. As the EJS, works with me too. Thank you @VernL

**Comment by VernL** [comment]
To close this issue, I am going to create an app using the [node express generator](https://expressjs.com/en/starter/generator.html) and add in our code.

**Comment by RichardLitt** [comment]
Works for me!

**Comment by RichardLitt** [comment]
@ZJaf If this is closed, what does #49 deal with? :) Should we open a new issue?

**Comment by ZJaf** [comment]
@RichardLitt  I closed this cause at that time we decided to use express generator #49  as the boilerplate instead of create-react-app package and we decided not to use React at that time 😆  . I still keep this closed and look into other options as the boilerplate for react (or maybe nothing) 🙈  Regarding express generator #49 , I am not sure how much we really need this. I trust your judgment and Vernon's call on this.
