### ISSUE TITLE
Nodemon package

### ISSUE THREAD

**Issue by ZJaf** [RichardLitt/the-travel-shelf#45]
Shall we use ![nodemon](https://www.npmjs.com/package/nodemon) for our automatic re-running? If so then we need to update json package in the script section. what do you guys think?

**Comment by RichardLitt** [comment]
I think so! 

Go ahead and PR it.

**Comment by ZJaf** [comment]
If we solve issue #44 , We wouldn't need this anymore. How about I start with that, and then we look at this later?

**Comment by RichardLitt** [comment]
SGTM.

**Comment by ZJaf** [comment]
I found something elseeee for Automatic Refresh \~.~/ . ![Webpack](https://webpack.github.io/docs/webpack-dev-server.html)
honestly nodemon looks easier 😄  to implement

**Comment by RichardLitt** [comment]
Webpack does a lot more, AFAIK. And I believe it is more supported. :D

**Comment by ZJaf** [comment]
> Webpack does a lot more, AFAIK. And I believe it is more supported. :D 

@RichardLitt  getting to know Webpack, It is awesome, you are right. I will be back with a pull request soon.

**Comment by RichardLitt** [comment]
@ZJaf let's follow up with this! Is this still needed, do you think?

**Comment by ZJaf** [comment]
No, not really
