### ISSUE TITLE
Implement Oauth

### ISSUE THREAD

**Issue by ZJaf** [RichardLitt/the-travel-shelf#47]
Let's discuss the options with pros and cons to each.

**Comment by RichardLitt** [comment]
I have used Authy, Auth0, and passport. For this, I would probably use passport, unless there's a better plan. I always have issues with implementing OAuth.

**Comment by VernL** [comment]
I also vote for passport. I've used it once before as part of an online course and is relatively easy to implement.

**Comment by RichardLitt** [comment]
Let's go with Passport. @VernL - what do you think about doing a quick prototype in a branch?

**Comment by RichardLitt** [comment]
Can reopen later.
