### ISSUE TITLE
Learn GitHub-Flavoured Markdown

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#5]
Please write a response to this issue in Markdown, showing you know how to use: a header, a link, an image, and bullet points.

**Comment by Jojokats** [comment]
Reviewed Markdown CheatSheet and know how to use a header, link, image & bullet points.

**Comment by RichardLitt** [comment]
Thanks @Jojokats! Can you put it in an issue here?

## Example

Anyone want to learn [Tokelauan?](https://en.wikipedia.org/wiki/Tokelauan_language) Why? Because:
- It's awesome
- I want to sing songs from Moana in the original language. 

![](http://gifimage.net/wp-content/uploads/2017/08/moana-gif-2.gif)

**Comment by HanieJ** [comment]
###### Fast Version:

# Markdown is cool!
+ why?
   + It is __not__ another _language_!
   + Learning is as fun as a language
   + [Make everything minimalist!](https://bemorewithless.com/25-reasons-you-might-be-a-minimalist/)

I AM READY |^_^|
![Unagi](https://media.giphy.com/media/j9T65td3Kjqko/giphy.gif)

**Comment by Jojokats** [comment]
#Markdown is amazingly useful!

######Here are **3 reasons** why *you* should learn it:

*You won’t need another goofy editor to write your next blog post
*[Markdown] (https://en.wikipedia.org/wiki/Markdown#Editors ) is amazingly useful and accessible to everyone
*It will make your life *easier* & you’ll work faster!


![image](https://user-images.githubusercontent.com/10158712/30620737-18a836c6-9d75-11e7-88ca-b5c97cf54b86.png)

**Comment by Jojokats** [comment]
# Markdown is amazingly useful!

### Here are **3 reasons** why *you* should learn it:

+ You won’t need another goofy editor to write your next blog post
+ [Markdown](https://en.wikipedia.org/wiki/Markdown#Editors ) is amazingly useful and accessible to everyone
+ It will make **your life easier** & you’ll work faster!

![popkey](https://m.popkey.co/d10d81/4jrED.gif)

**Comment by VernL** [comment]
# GitHub Flavored Markdown 
## About
- GitHub's syntax for formatting text.
- Easy to read, easy to write syntax for formatting plain text. 
  - Used to format **pose** and **code** across the site. 
  - Used to interact with user features such as  @mentions, task lists, links to issues & pull requests. 

    >Such quote, much happy.
[Author](https://www.google.ca/search?q=doge&num=100&rlz=1C1CHBF_enCA747CA747&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiGj_v84bLWAhWExYMKHUYVBJAQ_AUICigB&biw=2133&bih=1055)
![alt text](http://i0.kym-cdn.com/entries/icons/original/000/013/564/doge.jpg "<3")

- Markdown is:
  - [ ] Awesome
  - [x]  Super-Awesome

**Comment by hammerhead79** [comment]
# Markdown is *Easy,* *Simple* but **Awesome!!!** :sunglasses:
## Thanks! @RichardLitt for sharing this to our group.

### Things to do today.
- run for 30 min at least twice a day.
- learn to code **(Javascript)**
- learn GitHub Basics

### ![THE ATTACK OF THE PICKLE RICKS](https://blog.imgur.com/2017/08/11/the-attack-of-the-pickle-ricks/)
![attack](https://user-images.githubusercontent.com/25584914/30641007-66f0a652-9dd3-11e7-9960-d9fc5c6a7d71.gif)

**Comment by RichardLitt** [comment]
Awesome!
