### ISSUE TITLE
setting up react structure

### ISSUE THREAD

**Issue by ZJaf** [RichardLitt/the-travel-shelf#51]
I would break down the home page to components and put them in the component folder. This way @Jojokats  and I we can choose which component to work on.  Also from the project structure, I recommend having index.js in the src folder and components as a separated folder inside src. 

I do not know where to put index.html yet. I will update this issue when I found out.
I make a PR with my changes. Any ideas, thoughts are welcome.

**Comment by Jojokats** [comment]
I'm working on a React course and should get an answer to this shortly regarding the structure

**Comment by ZJaf** [comment]
@Jojokats  no rush, we will also look at it this Thursday

**Comment by Jojokats** [comment]
Just discovered how to implement Bootstrap with Reactjs and made a small App to test it and it works. Yeah!!!! 
This includes index.html and the src directory. We can implement a components directory and have all our components live in hear. Yeah!!!!

**Comment by Jojokats** [comment]
Can show you @ZJaf Monday how I did it.

**Comment by VernL** [comment]
My vote is to use create-react-app to get up and running with a standard build.

**Comment by RichardLitt** [comment]
Do it. PR time. :)

**Comment by ZJaf** [comment]
@VernL @RichardLitt  I suggest we create our own setup and structure means no boilerplate :D

**Comment by ZJaf** [comment]
I found this ![article](https://www.codementor.io/goodnesskay/setting-up-react-with-webpack-3-0-yarn-and-babel-9ftd5phqz) which will help us setup all the basic packages to run a react app with out using a boiler plate.
