### ISSUE TITLE
React routing vs Express routing

### ISSUE THREAD

**Issue by ZJaf** [RichardLitt/the-travel-shelf#52]
Everyone, let's do some study and research on this. I am not sure which one is more appropriate for our platform and why! 

Shoot your ideas here

**Comment by VernL** [comment]
Since we are going with React, I suggest we use React routing.

**Comment by RichardLitt** [comment]
Works for me. Get it set up?

**Comment by ZJaf** [comment]
What I figured out is that, React routing is great for connecting views(react components) together but when it comes to connecting to db with nodejs, we probably need a Node routing system. I am working on react routing it as well. I would like it to be as simple as possible and only necessary codes we need.
