### ISSUE TITLE
Create Schema for bookstore data

### ISSUE THREAD

**Issue by VernL** [RichardLitt/the-travel-shelf#64]
Please see doc on google drive --> [here](https://docs.google.com/document/d/1VtDP04wvfH5U-FSniD-xDOfKVYCDinrfrqf0wMDQR3k/edit)

**Comment by ZJaf** [comment]
I added my comments in blue

**Comment by RichardLitt** [comment]
Added some comments.

**Comment by RichardLitt** [comment]
@VernL Can you add this in a markdown file in Docs? I don't think this should be in Google Drive. It would be great to be able to track changes from #89.

**Comment by VernL** [comment]
Yes! I was going to suggest that we add a short form description for the listings page.

**Comment by RichardLitt** [comment]
Add it, then. :)
