### ISSUE TITLE
Heading_Section Component

### ISSUE THREAD

**Issue by ZJaf** [RichardLitt/the-travel-shelf#65]
Creating a Component called Heading_Section, including only a Text (about the project). 

This component needs to have a reference to the homepage scene, index.js

check this picture for better understanding Homepage Breakdown structure.
https://drive.google.com/open?id=0BzCdW9VLdR34dm50a3h0STVEMmc

**Comment by RichardLitt** [comment]
Who wants to take this one?

**Comment by ZJaf** [comment]
Not sure if this is really needed anymore. @VernL what do you think?

**Comment by RichardLitt** [comment]
Not useful at the moment. All good.
