### ISSUE TITLE
Fonts for The Travel Shelf

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#70]
Hey all, have a look at the fonts in the index.html.

We're using for the Heading: Muli
and for the Body: Ovo

This was researched via https://femmebot.github.io/google-type/  that Richard provided.
Please give me your feedback.
Thanks!

**Comment by VernL** [comment]
LGTM!

**Comment by ZJaf** [comment]
I like them, Thank you @Jojokats
