### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#71]
Hey all, 
FYI The images are from unsplash and pexels so they are free to use. I will double check though. The only one that isn’t is the map. I had to use this one temporarily  because I couldn’t find another one. If you guys can provide one for the map this would be awesome, just let me know!
Thanks!

**Comment by RichardLitt** [comment]
> so they are free to use.

Free to use doesn't mean free to use without attribution. Can you check that we don't need to attribute them? What is the license? 

> I had to use this one temporarily because I couldn’t find another on

You mean that we can't have the map legally? In that case, please remove it.

**Comment by Jojokats** [comment]
>Free to use doesn't mean free to use without attribution. Can you check that we don't need to attribute them? What is the license?

## License

All photos published on Unsplash can be used for free. You can use them for commercial and noncommercial purposes. You do not need to ask permission from or provide credit to the photographer or Unsplash, although it is appreciated when possible.

More precisely, Unsplash grants you an irrevocable, nonexclusive copyright license to download, copy, modify, distribute, perform, and use photos from Unsplash for free, including for commercial purposes, without permission from or attributing the photographer or Unsplash. This license does not include the right to compile photos from Unsplash to replicate a similar or competing service.

### Questions? Read our FAQ.

### Tip: How to give credit 🎁
Even though credit isn't required, Unsplash photographers appreciate a credit as it provides exposure to their work and encourages them to continue sharing. A credit can be as simple as adding their name with a link to their profile or photo:

Photo by Jeremy Bishop on Unsplash
[Read more]( https://unsplash.com/license)

**Comment by Jojokats** [comment]
I'm going to have to remove it and replace it.
I'm looking for another free one. will get back to you

**Comment by Jojokats** [comment]
I found a map replacement for now and it's CC0. Will be uploading it soon and can always be changed later if required.
