### ISSUE TITLE
Add .vscode to .gitignore

### ISSUE THREAD

**Issue by ZJaf** [RichardLitt/the-travel-shelf#73]
@Team,Is it ok to with you updating .gitignore with another line to ignore .vscode?

I added .vscode(a setting.json file)  that helps Visual Studio Code to determine the ReactComponents automatically.

**Comment by Jojokats** [comment]
I guess you have to do what works.

**Comment by VernL** [comment]
@Zjaf, Is it something that we all need or could it go in your global git ignore file??

I made one to inlude the .idea folder from webstorm...

Info is --> [Here](https://help.github.com/articles/ignoring-files/)

**Comment by RichardLitt** [comment]
> @ZJaf, Is it something that we all need or could it go in your global git ignore file??

Exactly. :)

**Comment by ZJaf** [comment]
>@Zjaf, Is it something that we all need or could it go in your global git ignore file??
I believe it is local as I might be the only one who is using VS.

Thank you all for the answers and thanks @VernL  for the article. I close this issue.
