### ISSUE TITLE
Add one bookstore for help with stubbing front end

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#74]
This one is on me!

**Comment by Jojokats** [comment]
Hey @RichardLitt  just wondering if I will also be working on bookstore page.

**Comment by RichardLitt** [comment]
If you'd like to!

**Comment by Jojokats** [comment]
Yes, I would! 
Not sure how you want to proceed. Should I just start and then show it to you? 
What feature will you be working on?

**Comment by RichardLitt** [comment]
I will be working on getting you content for this. Wait until I am done, if you could!

**Comment by Jojokats** [comment]
OK, don't mean to push but can you give me a time estimate, just to plan my schedule.
I started on the blog, but guess I will have to  stop.

**Comment by RichardLitt** [comment]
Not today. I can't keep responding to you at this rate, I'm sorry.

**Comment by Jojokats** [comment]
ok, no worries.

**Comment by Jojokats** [comment]
I finished coding a mockup for the blog and a Bookstore page the way I imagined it. I can show it at the next meeting and do the modifications that are required.
