### ISSUE TITLE
List three reasons for and against using Ruby and Rails

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#8]
Go!

**Comment by Jojokats** [comment]
# Advantages for using Ruby on Rails:
1- 	Code Quality - Generally, we find the quality of third party Ruby code to be significantly higher than their PHP or NodeJS equivalents.

2- 	Libraries - There's a gem (3rd party module) for just about anything you can think of. They are all publicly available and searchable through https://rubygems.org/.

3- 	Tooling - Rails provides fantastic tooling that helps you to deliver more features in less time. It provides a standard structure for web apps, where all the common patterns are taken care of for you.

# Disadvantages

1- Runtime Speed - The most cited argument against Ruby on Rails is that it's "slow". We would agree, certainly when compared to the runtime speed of NodeJS or GoLang.

2- Documentation - It can be hard to find good documentation. Particularly for the less popular gems and for libraries which make heavy use of mixins (which is most of Rails). 

3-  Multithreading - Rails supports multithreading, though some of the IO libraries do not, as they keep hold of the GIL

**Comment by HanieJ** [comment]
I like _infographics_. Voila __Pros__ and __Cons__ of Ruby!
![ruby](https://qph.ec.quoracdn.net/main-qimg-d251efe7b6c4e7d2a19b1d07b6017293.webp)
And also the job market that I was talking about today:
![stat](https://cdn-images-1.medium.com/max/800/1*7Va2xnJbgXenQ95RAkhuAQ.jpeg)

**Comment by hammerhead79** [comment]
![ruby](https://user-images.githubusercontent.com/25584914/30647437-6cbd34b8-9de9-11e7-93b9-975acecc8335.png)
![benchmark](https://user-images.githubusercontent.com/25584914/30647668-0a492d2c-9dea-11e7-8fd9-dd3d1c436353.png)

**Comment by RichardLitt** [comment]
Hey! Cool. What's the source for this image?

**Comment by VernL** [comment]
## Pro's
- Open source community with more than 4500 contributors 
- Built to make the programmer happy! (Item \# 1 of the rails [Doctrine](http://rubyonrails.org/doctrine/))
- Fast and powerful to allow for high productivity.

## Con's
- Active repositories rank on GitHub declined from \# 2 in Q2/12 to \# 6 in Q4/14 suggesting the popularity of the language is in decline. ( [source ](http://githut.info/))

**Comment by RichardLitt** [comment]
Thanks all!
