### ISSUE TITLE
Modified files to commit

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#80]
Hey Richard,
I am using CodeKit to compile scss files, (I usually use the command line but for some reason was not working tonight).
My question is that it created the following files and do not know what to do with them:
```
        config.codekit
	css/style.css.map
	scss/.sass-cache/
```
Do I delete them or push them?
Also for some reason it says that `index.js` was modified but I never touched it so don't know what to do with this one either.
Please advise,
Thanks!

**Comment by RichardLitt** [comment]
You need to add these to your global gitignore. 

The index.js file sounds like a different issue. Run `git diff` and tell me what the actual diff is that is making it think it is modified.

**Comment by Jojokats** [comment]
This is what I get with `git diff`

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	config.codekit
	css/style.css.map
	index.js
	scss/.sass-cache/

no changes added to commit (use "git add" and/or "git commit -a")
JoannaKats:the-travel-shelf joannakatsifaraki$ git pull
Already up-to-date.
JoannaKats:the-travel-shelf joannakatsifaraki$ git merge origin/master
Already up-to-date.
JoannaKats:the-travel-shelf joannakatsifaraki$ git diff
diff --git a/img/world.png b/img/world.png
deleted file mode 100644
index 1b8f4cf..0000000
Binary files a/img/world.png and /dev/null differ

**Comment by Jojokats** [comment]
This is what I get with git diff

Untracked files:
(use "git add ..." to include in what will be committed)

config.codekit
css/style.css.map
index.js
scss/.sass-cache/
no changes added to commit (use "git add" and/or "git commit -a")
JoannaKats:the-travel-shelf joannakatsifaraki$ git pull
Already up-to-date.
JoannaKats:the-travel-shelf joannakatsifaraki$ git merge origin/master
Already up-to-date.
JoannaKats:the-travel-shelf joannakatsifaraki$ git diff
diff --git a/img/world.png b/img/world.png
deleted file mode 100644
index 1b8f4cf..0000000
Binary files a/img/world.png and /dev/null differ

**Comment by RichardLitt** [comment]
Please edit your comments and put the results of your terminal requests in code blocks. These are hard to read.

**Comment by Jojokats** [comment]
```
git diff
diff --git a/img/world.png b/img/world.png
deleted file mode 100644
index 1b8f4cf..0000000
Binary files a/img/world.png and /dev/null differ
```

**Comment by RichardLitt** [comment]
It doesn't look like index.js is any different. Weird. Just reset it so that there are no differences. 

Google "what are css map files", and "what are sass-cache files", and whether you should commit them. This will help inform you.

**Comment by Jojokats** [comment]
what do I google, how to reset a git file?

**Comment by RichardLitt** [comment]
Type the command `git status` and read the output.
