### ISSUE TITLE
Modify navbar menu

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#83]
Hey all,

Would like your feedback. 

There's not much real estate on the menu and need to insert a link for Blog so I was thinking of modifying the navbar menu as shown in the picture below.
Please let me know what you think, if you have any other suggestions, please share!

Thanks

![image](https://user-images.githubusercontent.com/10158712/32275029-1469faf4-bee0-11e7-8f8a-b37c1b9fc2dc.png)

**Comment by VernL** [comment]
Just a thought, we may not need admin in the drop down as the site should be able to detect when a user with  admin privileges has signed in. 

But it LGTM

**Comment by Jojokats** [comment]
Thanks @VernL for your feedback!

**Comment by RichardLitt** [comment]
I would remove blog - we don't have a blog at the moment! I'm also not sure we need admin or users yet. We should add those when we have users.

**Comment by Jojokats** [comment]
OK, just started working on the blog :(

If I understand correctly, I only keep:
Home
About
Bookstores
Contact
Search

and remove the rest?

**Comment by RichardLitt** [comment]
Sounds right to me. I don't think search goes anywhere at the moment. 

> OK, just started working on the blog :(

What does the blog look like?

**Comment by Jojokats** [comment]
> What does the blog look like?

I think it's nice, but don't want to show it yet, waiting to get more done first.

**Comment by Jojokats** [comment]
> Sounds right to me. I don't think search goes anywhere at the moment.

I included `Search` because I think we will be using it for the React components.

**Comment by Jojokats** [comment]
I finished coding a mockup for the blog and can show it at the next meeting.

**Comment by RichardLitt** [comment]
Sorry, maybe I should have been more clear.

What do you imagine going on the blog? Why is there a blog? What will be written on the blog?

**Comment by Jojokats** [comment]
> Sorry, maybe I should have been more clear.
What do you imagine going on the blog? Why is there a blog? What will be written on the blog?

Blogging is important, it helps you connect with your readers and it's good for SEO, so yeah, I think a blog is important. You can talk about your recent visit to a bookstore you went to like a recent visit I made to Shakespeare and Company... You can also have others contribute to the blogging as well! Makes the website feel alive and dynamic!

Here's a peak to the blog page I coded.
![blog](https://user-images.githubusercontent.com/10158712/32357496-ad9a0744-c013-11e7-9261-eecf4be5962b.png)

**Comment by Jojokats** [comment]
I finished coding the mockup of the blog and Bookstore page. I can send images if you want.

**Comment by RichardLitt** [comment]
> Blogging is important, it helps you connect with your readers and it's good for SEO, so yeah, I think a blog is important. You can talk about your recent visit to a bookstore you went to like a recent visit I made to Shakespeare and Company... You can also have others contribute to the blogging as well! Makes the website feel alive and dynamic!

Blogging would be important for other sites who wish to engage with their users and to rank their SEO. But this site is already a media site - the bookstore profiles themselves are content, coming out on a dated basis. Having a blog on top of this detracts from the goal of the site. We also won't be profiling specific recent visits to bookstores on this site.

**Comment by Jojokats** [comment]
> Blogging would be important for other sites who wish to engage with their users and to rank their SEO. But this site is already a media site - the bookstore profiles themselves are content, coming out on a dated basis. Having a blog on top of this detracts from the goal of the site. We also won't be profiling specific recent visits to bookstores on this site.

OK, will not include Blog on menu.

Will include only:
* Home
* About
* Bookstores
* Contact
* Search
