### ISSUE TITLE
User Flows

### ISSUE THREAD

**Issue by Jojokats** [RichardLitt/the-travel-shelf#88]
Hey all,
Just prepared a User flow for the website to better understand how it works so that the code can be linked to the right pages. Let me know if there’s any modifications or corrections. Thanks!

![image](https://user-images.githubusercontent.com/10158712/32423754-60c73d64-c276-11e7-98f9-f9af73898112.png)

**Comment by RichardLitt** [comment]
This looks good to me! I think there would be a good bit more writing on the Bookstores page than this, however. They're not so much informative as profiles, in the first few versions of the website as I envision.

**Comment by Jojokats** [comment]
I can always update the flow for the Bookstores page once it's established. Let me know what you want me to update for the rest of the pages.
