### ISSUE TITLE
List three reasons for and against using Rust

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#9]

**Comment by Jojokats** [comment]
#Pros 
+ More like C++ and Go, less like Node and Ruby
+ Rust’s language goal is to enable fast, efficient, and memory safe systems programming

#Cons 
+ simplicity has never been touted as one of its design fundamentals.
+ Not a lot of documentation, 
+ Now that Rust has reached 1.0, the language is guaranteed to be “stable”; and while it may continue to evolve, code which works on current Rust should continue to work on future releases. 
+ Not Job demanded in Montreal

**Comment by RichardLitt** [comment]
I think we can rule this one out: lack of documentation, job demand, and long term stability is enough of a reason to steer clear for this project.
