### ISSUE TITLE
Implement markdown parser into frontend

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#96]
Because the writers are going to be using markdown, because.

**Comment by RichardLitt** [comment]
Only needed if we have a writing field. @VernL We have a post request - do we have a view for this?

**Comment by VernL** [comment]
Currently posting data via Postman. This will be a fun one, if it's still open I'll build a view after #47.

**Comment by RichardLitt** [comment]
Closing to clean out issues. Can reopen later.
