### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/the-travel-shelf#99]
## About

The Travel Shelf is a joint enterprise by Richard Littauer and students from the Les Pitonneux coding school in Montréal, Canada. Richard goes to a lot of bookstores, and wanted a way to talk about those bookstores. The students - Vernon, Joanna, Hanie, and Jose - wanted to build a website together. This is the result. 

Interested in adding a bookstore, yourself? Want to join the team? Get in touch. 

info@thetravelshelf.com.

**Comment by RichardLitt** [comment]
Here is another page to look at https://wordhoardpress.com/about/

About should be the same as contact.

**Comment by Jojokats** [comment]
Nice website!
